### PR TITLE
Update AwesomeEditText.kt

### PR DESCRIPTION
**Pull request by razavioo**
Add the ability for other classes to inherit this class.

### CODE REVIEW

**Comment by anoop44** [comment]
Do you mind for what use case are you extending this class? If something related to the animation of edittext, maybe we can add to this library

**Comment by razavioo** [comment]
I am generating a puzzle crossword game and realized that I may use your module to improve my UI. it is not related to adding some features related to your nice project.

**Comment by anoop44** [comment]
cool. Merging it now. Will release a new version soon

**Comment by anoop44** [comment]
v1.1.0 has been released. It has this change

**Pull request merged**
